### ISSUE TITLE
Problem running script on Ubuntu with dependencies installed

### ISSUE THREAD

**Issue by clhenrick** [talos/nyc-stabilization-unit-counts#2]
I get the following error:

```
$ python download.py '146' 'Fenimore Street' 'Brooklyn'

146 Fenimore Street, Brooklyn
Traceback (most recent call last):
  File "download.py", line 88, in <module>
    main(sys.argv[1], sys.argv[2], sys.argv[3])
  File "download.py", line 29, in main
    bbl = '{}-{}-{}'.format(form['q49_boro'],
KeyError: 'q49_boro'
```

**Comment by clhenrick** [comment]
Nevermind, looking at the POST request I see that borough should be specified as a number. Also perhaps doing a check for a `data` directory would before doing the check for `data/bbl-number`. Maybe I'll submit a pull request :)
